org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn
net.minecraftforge.gradle.merge-source-sets=true

## Mod metadata - substituted into mods.toml and pack.mcmeta at build time
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2,)
forge_version=64.0.5
forge_version_range=[64,)
loader_version_range=[64,)
mod_id=immersivefoods
mod_name=ImmersiveFoods
mod_license=All Rights Reserved
mod_version=26.1.2-0.0.1
mod_authors=EPIICTHUNDERCAT
mod_description=Adds food items from various Minecraft mobs! We need more food!
